version: '3.7'
services:
  selenoid:
    container_name: selenoid
    image: aerokube/selenoid:latest
    volumes:
      - "$PWD/selenoid_config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/selenoid_config/video:/opt/selenoid/video"
      - "$PWD/selenoid_config/logs:/opt/selenoid/logs"
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "task11_docker_compose_test_net"]
    ports:
      - "4444:4444"
    networks:
      - test_net

  selenoid-ui:
    image: aerokube/selenoid-ui
    container_name: "selenoid-ui"
    links:
      - selenoid
    ports:
      - "8080:8080"
    networks:
      - test_net
    command: ["--selenoid-uri","http://selenoid:4444"]

  tests:
    container_name: tests
    build: .
    volumes:
      - "$PWD/allure-report:/app/allure-report"
      - "$PWD/allure-results:/app/allure-results"
    command: pytest --b_version 99.0  --browser chrome
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - test_net

  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/allure-results:/app/allure-results
      - ${PWD}/allure-reports:/app/default-reports

networks:
  test_net:

